### ISSUE TITLE
BUG: Hotbar & other positions messed up with 1.6.6

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#133] opened 2023-10-25 21:39 UTC
The position of a bunch of stuff gets messed up with this latest version of Minimal UI. Setting the Hotbar to Manual seems to default 0 to the center of the screen now. Having the Player List window minimized, but then clicking on it which expands it out, seems to shift both the Hotbar and the Scene List at the top of the screen to the side. I'm sure there's probably other positional issues too but I just downgraded to resolve them.

**Comment by saif-ellafi** [comment] 2023-10-25 21:42
Thanks for letting me know, I'll try to figure out what's wrong. The scene navigation moving to the right I could reproduce, but not the Hotbar moving.

**Comment by GambetTV** [comment] 2023-10-25 21:44
My settings for that were to set the hotbar position to manual, with the position set to 100. In the previous version this would put it very far to the left, almost to the point that it was in contact with the player list. In the latest version 100 puts the leftmost side of it in the center of the screen, or close to it.

**Comment by saif-ellafi** [comment] 2023-10-25 21:45
Got it, yeah, I didn't see that coming but true a side effect is the change of the meaning of the relative values. The number seems to be way more sensitive now.

**Comment by saif-ellafi** [comment] 2023-10-25 22:32
Ha, I found the bug. I was adding 400 + 0, which was read as '4000' hence the sensitivity of the hotbar lol. Dang I'm getting rusty. Will fix in a moment

**Comment by saif-ellafi** [comment] 2023-10-25 23:05
Hi @GambetTV - mind giving me a second chance and test?

**Comment by GambetTV** [comment] 2023-10-26 23:18
It mostly seems good, but when the player list goes from minimized to expanded (as in, when you can only see the dots to you can see the player's names) the hotbar shifts to the right, which it didn't do before.

**Comment by saif-ellafi** [comment] 2023-10-27 11:52
Cool, I couldn't reproduce that moving hotbar but will see.

**Comment by saif-ellafi** [comment] 2023-10-27 12:08
You sure you tried Minimal UI **1.6.7** @GambetTV ? I can't reproduce the scene navigation moving or the hotbar shifting upon expanding the player's list anymore.

**Comment by GambetTV** [comment] 2023-10-27 13:14
Yeah, it's 1.6.7, but it seems like it might be a bug caused by your module interacting with the module "Monk's Hotbar Expansion." However, it's gotta be your module causing the issue, because it works fine in 1.6.5, and MHE hasn't been updated in over a year.

**Comment by saif-ellafi** [comment] 2023-10-27 13:16
Ahh gotcha, yes I might have broken specific module compatibility with Monk's. Will check quickly.

**Comment by saif-ellafi** [comment] 2023-10-27 13:53
Alright, I reviewed this. @GambetTV - this really isn't my fault. This used to work because the player's list was hardcoded, just like Monk's. Now Minimal UI behaves like Foundry VTT does, which is cleaner and more compatible.

The fix needs to be done on Monk's side, to not have a fixed position on his side. But the current approach in Minimal UI is the best for the bigger picture.

**Comment by GambetTV** [comment] 2023-10-27 14:06
Okay, no worries. I'll put in a ticket for Monk's, although I'm not sure I'll hold my breath it'll ever get resolved, as the module hasn't been updated in over a year. In the meantime I'll probably have to downgrade to 1.6.5 just to make sure everything stays working. Thanks for looking into it though!

**Comment by GambetTV** [comment] 2023-10-27 14:08
Actually, now that I think about it this might be even better. I suppose I can just remove the buffer, which will save me more space here since I mostly have the player list minimized anyway. TBH I didn't really think about the utility of it, I just saw that it didn't work how it used to and assumed it was a bug.

**Comment by saif-ellafi** [comment] 2023-10-27 14:09
Thanks - in any case, I just found a way to make an exception and make them work together for a longer while. Will release soon, but yeah it is mostly an exception **specifically** for Monk's hotbar. Maybe there are other users who want to use both

**Comment by saif-ellafi** [comment] 2023-10-27 14:27
Really fixed now, compatibility with Monk's Hotbar for a longer while :)

**Closed by saif-ellafi** 2023-10-27 14:27 UTC
Labels: bug, fixed
